site_name: nnio - Neural Networks inference on accelerators simplified.
nav:
  - Home: index.md
  - Basic Usage:
    - ONNX: basic_onnx.md
    - EdgeTPU: basic_edgetpu.md
    - OpenVINO: basic_openvino.md
  - Model Zoo:
    - Model Zoo: model_zoo.md
  - Utils:
    - Model Class: model_class.md
    - Preprocessing: preprocessing.md
    - Outputs: output.md

theme:
  name: readthedocs
  palette:
    primary: brown

markdown_extensions:
  - attr_list