site_name: nnio - Neural Networks inference on accelerators simplified.
nav:
  - Home: index.md
  - Installation: install.md
  - Basic Usage:
    - ONNXModel: basic_onnx.md
    - EdgeTPUModel: basic_edgetpu.md
    - OpenVINOModel: basic_openvino.md
  - Model Zoo:
    - Model Zoo: model_zoo.md
  - Utils:
    - Model Class: model_class.md
    - Preprocessing: preprocessing.md
    - Outputs: output.md

theme:
  name: readthedocs
  palette:
    primary: brown

markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - mkautodoc

# plugins:
#   - mkdocstrings